Optional icon in TableExpandHeader that is shown instead of the default icons
eccenca/gui-elements pull request #133
Opened 2023-10-13 13:23 UTC by andreas-schultz

2023-10-13 15:20 UTC, arausly submitted a review, later dismissed

2023-10-16 07:45 UTC, haschek requested changes

2023-10-16 07:45 UTC, haschek commented on src/components/Table/TableExpandHeader.tsx
> +    toggleIcon?: ValidIconName | string[] | React.ReactElement<TestIconProps>;
Please add description.

2023-10-16 08:25 UTC, haschek approved these changes

2023-10-16 08:25 UTC, merged