Codemirror component changes
eccenca/gui-elements pull request #154
Opened 2024-03-07 09:08 UTC by arausly

1. Added support for code folding
2. Changed default json mode to jsonld
3. added addons for code-formatting

2024-03-19 11:24 UTC, andreas-schultz commented on src/extensions/codemirror/CodeMirror.tsx
> +        editorInstance.on("scroll", (instance) => {
Only register the scroll handler when `onScroll` is defined.

2024-03-19 11:24 UTC, andreas-schultz commented on src/extensions/codemirror/CodeMirror.tsx
>          editorInstance.on("change", (api) => {
same here.

2024-03-19 13:22 UTC, haschek requested changes
Please do  not forget to update the changelog regarding new features, properties, fixes, changes.

2024-04-10 07:32 UTC, andreas-schultz submitted a review, later dismissed

2024-04-10 10:36 UTC, haschek approved these changes

2024-04-10 10:46 UTC, haschek requested changes

2024-04-10 10:46 UTC, haschek commented on src/extensions/codemirror/CodeMirror.tsx
> +import React, {TextareaHTMLAttributes, useEffect, useRef} from "react";
@andreas-schultz is it possible that different linting rules are used here? Otherwise there shouldn't be changes?

2024-04-10 10:46 UTC, haschek commented on src/extensions/codemirror/CodeMirror.tsx
> +    onChange?: (v: any) => void;
What was the reason to change this from mandatory to optional?

2024-04-10 10:46 UTC, haschek commented on src/extensions/codemirror/CodeMirror.tsx
> +    const jsonModifierClassName = mode === "json" ? `${eccgui}-json-modifier` : "";
Class name not valid against BEM guidelines, should probably be `${eccgui}-codeeditor--mode-json`. And this class should be set for all modes (then probably `${eccgui}-codeeditor--mode-${mode}`), even if we only use it for `json` later in the stylesheets.

2024-04-10 10:46 UTC, haschek commented on src/extensions/codemirror/_codemirror.scss
> +.#{$eccgui}-json-modifier {
Update class name regarding change in tsx.

2024-04-11 14:00 UTC, haschek approved these changes

2024-04-11 19:38 UTC, merged