Add linters to code editor
eccenca/gui-elements pull request #218
Opened 2024-11-21 06:53 UTC by emir89

2025-01-30 10:22 UTC, haschek commented on src/extensions/codemirror/CodeMirror.tsx
>              data-test-id="codemirror-wrapper"
`"codemirror-wrapper"` should only be used if `data-test-id` is not given. Please add also a `// @deprecated (v25) fallback with static test id will be removed` comment here.

2025-01-30 10:24 UTC, haschek commented on src/extensions/codemirror/CodeMirror.tsx
> +            data-testid={dataTestId ? `${dataTestId}_codemirror}` : undefined}
We probably don't need to alter the test id by a suffix, the developer could use `xyz_codemirror` directly.

2025-01-30 12:34 UTC, haschek requested changes
1. review for CMEM-5464 (linting).

2025-01-30 12:34 UTC, haschek commented on src/extensions/codemirror/CodeMirror.tsx
> +     * Enables linting feature in the editor.
Please add what modes currently can use linting.

2025-01-30 12:34 UTC, haschek commented on src/extensions/codemirror/_codemirror.scss
> +            min-height: 290px;
This (and the other) `min-height: 290px;` rule leads to a visual bug here: https://62150dbccb2d77003a2a5093-dulpfvcgaz.chromatic.com/?path=/story/forms-codeautocompletefield--default

2025-02-03 07:09 UTC, emir89 commented on src/extensions/codemirror/_codemirror.scss
> +            @extend .#{$ns}-input, .#{$ns}-intent-warning;
In the previous review you asked me to check if we could use  Blueprint's intent classes here. We could, and yes I could just use them for the rest or our intent classes but it introduces  unnecessary complexity.  After checking it seems like we don't have to use all rules from `.#{$ns}-input`  but `pt-input-intent`  definitely seems as a more simple and clear approach as well as consistent  one within the library.

2025-02-03 07:10 UTC, emir89 commented on src/extensions/codemirror/types.ts
> +export enum EditorMode {
It's possible, I adjusted it.

2025-02-04 14:40 UTC, haschek approved these changes

2025-02-04 14:41 UTC, merged