Feature/change node width CMEM 4051
eccenca/gui-elements pull request #219
Opened 2024-11-21 09:30 UTC by arausly

Feature to adjust node width to a set maximum.

2025-02-19 14:32 UTC, haschek requested changes
1st review. Please also add info to changelog.

2025-02-19 14:32 UTC, haschek commented on src/extensions/react-flow/_config.scss
> +$react-flow-cursor-delimiter-offset: -6.5 * $reactflow-node-border-width;
Please keep the naming pattern like the other `$reactflow-*` variables (not `$react-flow-*`).
And this white space value should not be bound to a border width. It should be probably `$eccgui-size-block-whitespace` (or half of it).

2025-02-19 14:32 UTC, haschek commented on src/extensions/react-flow/nodes/NodeContent.tsx
> +    resizeDirections?: Enable;
As we do not support all resize directions, only the supported directions from `Enable` should be available via `resizeDirections`.

2025-02-19 14:32 UTC, haschek commented on src/extensions/react-flow/nodes/NodeContent.tsx
> +    const isResizable = !!onNodeResize && minimalShape === "none";
Misses test on correct condition for `resizeDirections`, currently the resize container is also used for a value of `{}` or `false` for every direction.

2025-02-24 11:02 UTC, haschek requested changes
2nd review. Changelog updates are still missing, too.

2025-02-24 11:02 UTC, haschek commented on src/extensions/react-flow/nodes/NodeContent.tsx
> +        typeof onNodeResize === "function" && Object.keys(resizeDirections).length && minimalShape === "none";
This conditional check would activate resizing also for e.g. `resizeDirections={bottom: false}`, what would be not correct. At least one value for `bottom`, `right` and `bottomRight` need to be `true`

2025-02-27 17:01 UTC, haschek approved these changes

2025-03-12 08:38 UTC, andreas-schultz approved these changes

2025-03-12 09:11 UTC, merged